#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I/opt/X11/include
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lX11
LDFLAGS = -L/opt/X11/lib -lX11

INC_DEBUG = $(INC) -I../src
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/ugui-sim-x11

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/ugui-sim-x11

OBJ_DEBUG = $(OBJDIR_DEBUG)/ugui.o $(OBJDIR_DEBUG)/ugui_button.o $(OBJDIR_DEBUG)/ugui_textbox.o $(OBJDIR_DEBUG)/ugui_checkbox.o $(OBJDIR_DEBUG)/simulator.o $(OBJDIR_DEBUG)/ugui-sim-x11.o 

OBJ_RELEASE = $(OBJDIR_RELEASE)/ugui.o $(OBJDIR_RELEASE)/ugui_button.o $(OBJDIR_RELEASE)/ugui_textbox.o $(OBJDIR_RELEASE)/ugui_checkbox.o $(OBJDIR_RELEASE)/simulator.o $(OBJDIR_RELEASE)/ugui-sim-x11.o 

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/font || mkdir -p $(OBJDIR_DEBUG)/font
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/ugui.o: ugui.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ugui.c -o $(OBJDIR_DEBUG)/ugui.o

$(OBJDIR_DEBUG)/ugui_button.o: ugui_button.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ugui_button.c -o $(OBJDIR_DEBUG)/ugui_button.o

$(OBJDIR_DEBUG)/ugui_textbox.o: ugui_textbox.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ugui_textbox.c -o $(OBJDIR_DEBUG)/ugui_textbox.o

$(OBJDIR_DEBUG)/ugui_checkbox.o: ugui_checkbox.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ugui_checkbox.c -o $(OBJDIR_DEBUG)/ugui_checkbox.o

$(OBJDIR_DEBUG)/simulator.o: simulator.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c simulator.c -o $(OBJDIR_DEBUG)/simulator.o

$(OBJDIR_DEBUG)/ugui-sim-x11.o: sim/ugui-sim-x11.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sim/ugui-sim-x11.c -o $(OBJDIR_DEBUG)/ugui-sim-x11.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/font
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/font || mkdir -p $(OBJDIR_RELEASE)/font
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/ugui.o: ugui.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ugui.c -o $(OBJDIR_RELEASE)/ugui.o

$(OBJDIR_RELEASE)/ugui_button.o: ugui_button.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ugui_button.c -o $(OBJDIR_RELEASE)/ugui_button.o

$(OBJDIR_RELEASE)/ugui_textbox.o: ugui_textbox.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ugui_textbox.c -o $(OBJDIR_RELEASE)/ugui_textbox.o

$(OBJDIR_RELEASE)/ugui_checkbox.o: ugui_checkbox.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ugui_checkbox.c -o $(OBJDIR_RELEASE)/ugui_checkbox.o

$(OBJDIR_RELEASE)/simulator.o: simulator.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c simulator.c -o $(OBJDIR_RELEASE)/simulator.o

$(OBJDIR_RELEASE)/ugui-sim-x11.o: sim/ugui-sim-x11.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sim/ugui-sim-x11.c -o $(OBJDIR_RELEASE)/ugui-sim-x11.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/font
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

